[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build:netlify"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[context.production.environment]
  NODE_ENV = "production"
  GATSBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.erkenningen.nl/graphql"
  GATSBY_ERKENNINGEN_ADMIN_URL = "https://administratie.erkenningen.nl"
  GATSBY_ERKENNINGEN_SITE_TYPE = "content"
[context.develop.environment]
  NODE_ENV = "production"
  GATSBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
  GATSBY_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.erkenningen.nl"
  GATSBY_ERKENNINGEN_SITE_TYPE = "content"
[context.deploy-preview.environment]
  NODE_ENV = "production"
  GATSBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
  GATSBY_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.erkenningen.nl"
  GATSBY_ERKENNINGEN_SITE_TYPE = "content"
